/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import board.DefaultBoard;
import board.GameBoard;
import gameUserInterface.UIDesign;
import gameUserInterface.TerminalDesign;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        GameBoard board = new DefaultBoard();
        String status = board.BoardStatus();
        UIDesign printer = new TerminalDesign();
        printer.showGame(status);
    }
}
